name: network_checker
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
